// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NIJI_VideoPlayer","status":true,"description":"v1.1.0 Play videos wherever you want","parameters":{}},
{"name":"MZPlusQuickStart","status":true,"description":"<MZPlusQuickStart> Skips the title for fast testing. (Will only skip the title in dev mode).  Credit to Quasi.","parameters":{"Dev Mode Only":"false"}}
];
